In [10]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# Ergodicity of a spin array

As you saw in class, one way of describing ergodicity is **"the ability of a system to reach every possible configuration when given enough time"**.

In this exercise you will simulate a basic 1D spin array and will check if the system is ergodic or not.


## Part 1 - Ensemble Average

### Task 1.1 - generate a 1D spin array of size $l$

Hint: Use np.random.choice() for the convenience

In [ ]:
def generate_spin_array(length):
    '''
    Description:
    This function gets an integer which corresponds to length of the array we want to generate.
    Then the function generates a spin array (spin up = +1/2, spin down = -1/2) of the requested length.
    The spin array that the function generates should be random.

    Inputs:
    length - the length of the array 
    
    Outputs: 
    spin_array - the array of the spins

    Example:
    input: length = 5
    output: spin_array = [-0.5, 0.5, 0.5, -0.5, 0.5]   (The out put may vary as the spins generated are random)
    '''
    ### Write Your Code Below ###

    spins_array = None
    return 

length = 5
spins_array = generate_spin_array(length)
print(spins_array)

None


### Task 1.2 - generate $N$ 1d arrays of size $l$ and store them in a Matrix

Hint: use the function created in task 1.1.

In [ ]:
def generate_N_1d_arrays(N, length):
    '''
    Description:
    This function gets 2 number which corresponds to length of the array we want to generate and the number of arrays.
    Then the function generates N spin arrays of a certain length and stores them in a matrix.
    As before, the spin arrays that the function generates should be random.

    Inputs:
    N - number of arrays to generate
    length - the length of the array 
    
    Outputs: 
    matrix - a matrix that contains all the arrays. Each row is a different array. 
    ***For convenience return the matrix as a numpy array using the converation np.array(matrix)****

    Example:
    input: length = 5
           N = 3 
    output: matrix = [[-0.5  0.5 -0.5 -0.5  0.5]
                      [-0.5 -0.5 -0.5  0.5 -0.5]
                      [-0.5 -0.5  0.5 -0.5 -0.5]]
    '''
    ### Write Your Code Below ###
    
    matrix = None

    return

length = 6
N = 3
matrix = generate_N_1d_arrays(N, length)
print(matrix)

None


### Task 1.3 - calculate the magnetization of a 1D array

In [ ]:
def calculate_total_magnetization(spins_array):
    '''
    Description:
    This function gets a spins array and calculates the magnetization (sum of all spins).

    Inputs:
    spins_array = 1D array of spins like the one generated in task 1.1
    
    Outputs: 
    magnetization - the magnetization of the array

    Example:
    input: spins_array = [-0.5  0.5 -0.5 -0.5  0.5]
    output: magnetization = -0.5
    '''
    ### Write Your Code Below ###
    
    magnetization = None
    return 

length = 6
spins_array = generate_spin_array(length)
magnetization = calculate_total_magnetization(spins_array)
print(magnetization)

None


### Task 1.4 - calculate the average magnetization of $N$ 1D spin arrays

In [ ]:
def calculate_average_magnetization(spins_matrix):
    '''
    Description:
    This function gets a spins matrix (N arrays of length l) and calculates the average magnetization. (average magnetization per array).

    Inputs:
    spins_array = 2D array of spins like the one generated in task 1.2
    
    Outputs: 
    average magnetization - the average magnetization per array

    Example:
    input: spins_matrix = [[ 0.5  0.5 -0.5 -0.5  0.5  0.5]
                           [-0.5 -0.5 -0.5 -0.5  0.5  0.5]
                           [-0.5 -0.5 -0.5  0.5 -0.5 -0.5]]
    output: average_magnetization = -0.333
    '''
    ### Write Your Code Below ###
    
    average_magnetization = None
    return average_magnetization

length = 6
N = 100
spins_matrix = generate_N_1d_arrays(N, length)
average_magnetization = calculate_average_magnetization(spins_matrix)
print(average_magnetization)

None


### Task 1.5 - plot the average magnetization as a function of N

In [15]:
#Set simulation parameters: length, N_max (the maximal ensemble size)

#Create a list of all the ensemble sizes (N) from 1 to N_max

#Generate arrays for each ensemble size and calculate the average magnetization for each size

#Plot the average magnetization as function of the ensemle size, on the same figure plot the mean of all the average magnetization (should be a constant - use plt.axhline())


### Question - Explain what you see in the plot:

## Part 2 - Time Average

### Task 2.1 - generate a spin up 1D array of length $l$

In [ ]:
def generate_spin_up_array(length):
    '''
    Description:
    This function generates an array of only spin up. This will be used later to create our initial configuration for the time evolution of the system.

    Inputs:
    length - the length of the generated array
    
    Outputs: 
    spins_array - spin up array

    Example:
    input: length = 6
    output: spins_array = [0.5,0.5,0.5,0.5,0.5,0.5]
    '''
    ### Write Your Code Below ###

    spins_array = None
    return

print(generate_spin_up_array(5))

None


### Task 2.2 - Flip a random spin in the array

This is the time evolution of the system.

At each step we will flip a spin randomly. Later we will see how does the system evolve in time.

In [ ]:
def flip_spin_randomly(array):
    '''
    Description:
    This function flips 1 spin of a given array. This will be used as our simulation step (time evolution).

    Inputs:
    array - 1D spins array
    
    Outputs: 
    array_copy - a copy of the spins array but with 1 randomly fliped spin

    Example:
    input: array = [-0.5,0.5,-0.5,-0.5,-0.5,0.5]
    output: array_copy = [-0.5,0.5,-0.5,-0.5,0.5,0.5]
    '''
    ### Write Your Code Below ###

    array_copy = None
    return 

spins_array = generate_spin_array(5)
flipped_array = flip_spin_randomly(spins_array)
print(spins_array , flipped_array)

None None


### Task 2.3 - Time Evolution 

Here we will implement the time evolution of the system. 

The system start at an initial configuration (here we will choose a spin up only array as our initial configuration), for each step of the simulation we will change the system using the function defined in Task 2.2

In [18]:
# Set simulation parameters (Time ,unit step and array length i.e time = 100 sec, dt = 1 sec, length = 10)

# Calculate the amount of steps

#Create an array of all the timesteps of the simulation

#Generate the initial configuration

#Advance the system in time and for each new configuration calculate and save the magnetization.

#Plot the magnetization over time, on the same figure plot the mean in the same way as in Task 1.5